name: bazi_fengshui_app

packages:
  - packages/** # 告诉 Melos 在 packages/ 目录下寻找所有专案

scripts:
  # === BOOTSTRAP ===
  # 安装所有 Dart/Flutter 和 Node.js 依赖
  bootstrap:
    run: |
      melos exec --scope="app" -- flutter pub get
      melos exec --scope="core" -- flutter pub get
      melos exec --scope="functions" -- npm install
    description: Install dependencies for all packages.

  # === CLEAN ===
  clean:
    run: |
      melos exec --scope="app" -- flutter clean
      melos exec --scope="core" -- flutter clean
      melos exec --scope="functions" -- "rm -rf node_modules && rm -rf lib"
    description: Clean all packages.

  # === TESTING ===
  test:
    run: melos run test:app && melos run test:functions
    description: Run all tests for app and functions.

  test:app:
    run: melos exec --scope="app" -- flutter test
    description: Run tests for the Flutter app.

  test:functions:
    run: melos exec --scope="functions" -- npm run test
    description: Run unit tests for Firebase Functions.

  # === DEPLOYMENT ===
  deploy:functions:
    run: melos exec --scope="functions" -- firebase deploy --only functions
    description: Deploy Firebase Functions.

command:
  bootstrap:
    usePubspecOverrides: true